-- Optional fresh Supabase setup for MyBrixS Standalone Web App v0.1
-- Reuse your existing Supabase project/table/bucket if they already exist.

create table if not exists public.readings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  fruit_type text not null default 'unspecified',
  batch_id text,
  brix numeric,
  confidence text,
  boundary_position text,
  notes text,
  latitude double precision,
  longitude double precision,
  image_url text,
  farmer_note text
);

-- Storage bucket must be created in Supabase dashboard:
-- Bucket name: mybrixs-images
-- Public bucket: recommended for MVP image display in the app.
